### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by Lucav17** [bdJohnson72/CA-Projects-Front-End-#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_  4
* _Comment(s):_  Great job linkin your CSS file to your HTML and using good CSS selectors throughout your CSS file to target HTML elements.
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_  4
* _Comment(s):_ The site looks great! 
 
### Criteria 3: HTML Elements and Content
* _Score Level:_  4
* _Comment(s):_  Well done using div's and creating sections. This was very well done and shows a great understanding of HTML. Good job using indentation and ol's and ul's too!
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_  As before, well done with your CSS! One thing I would say is to create a CSS folder and then store your CSS in there!
 
### Overall Score: 16/16
Well done!

**Comment by bdJohnson72** [comment]
thanks Luca
